Event
|where EventLog == 'Microsoft-Windows-Sysmon/Operational'
|where EventID == 1
| where tostring(parse_xml(EventData).DataItem.EventData.Data[4]['#text']) has_any ("rundll32.exe","procdump.exe")
| where tostring(parse_xml(EventData).DataItem.EventData.Data[10]['#text']) has "lsass"
| project TimeGenerated, Computer, Process=tostring(parse_xml(EventData).DataItem.EventData.Data[4]['#text']), CommandLine=tostring(parse_xml(EventData).DataItem.EventData.Data[10]['#text'])